%YAML:1.0

# KAIST urban30 preset for original VINS-Fusion.
# Uses the same urban28-style local calibration reference.

imu: 1
num_of_cam: 1

imu_topic: "/imu/data_frd"
image0_topic: "/stereo/left/image_mono"
image1_topic: ""
output_path: "/tmp"

cam0_calib: "kaist_left_pinhole.yaml"
image_width: 1280
image_height: 560

estimate_extrinsic: 0

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [-0.006800215707, -0.015326089353, 0.999859424145, 1.71239,
           0.999976850550, -0.000339636746, 0.006795808309, -0.247401,
           0.000235435836, 0.999882490912, 0.015328044165, 0.11589,
           0, 0, 0, 1]

multiple_thread: 1

max_cnt: 200
min_dist: 30
freq: 10
F_threshold: 1.0
show_track: 1
flow_back: 1

max_solver_time: 0.04
max_num_iterations: 8
keyframe_parallax: 10.0

acc_n: 0.1
gyr_n: 0.01
acc_w: 0.001
gyr_w: 0.0001
g_norm: 9.81007

estimate_td: 0
td: 0.0

load_previous_pose_graph: 0
pose_graph_save_path: "/tmp/vins_fusion_kaist_pose_graph/"
save_image: 1
